- name: install Kubernetes
  hosts: "localhost"
  tasks:
    - name: install prerequisities
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg2
          - make
        state: present
        update_cache: true
      become: true

    - name: Create apt keyrings dir
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Kubernetes GPG key
      ansible.builtin.apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
        keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add Kubernetes apt repository
      apt_repository:
        filename: kubernetes.list
        repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /'
        state: present
     
    - name: Install Kubernetes components
      apt:
        pkg:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: true
        #allow_change_held_packages: false

    - name: Enable Kubelet service
      ansible.builtin.systemd:
        state: restarted
        enabled: true
        name: kubelet

      become: true

    - name: Add Docker gpg
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Get ubuntu version
      ansible.builtin.shell: lsb_release -cs
      register: ubuntu_version

    - name: Add Docker repository
      apt_repository:
        #repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable
        state: present

    - name: Install Docker and containerd
      apt:
        pkg:
          - containerd.io
          - docker-ce
        state: present
        update_cache: true
      become: true

    - name: Create containerd config dir
      ansible.builtin.file:
        path: /etc/containerd
        state: directory
        mode: '0755'

    - name: Write containerd config
      ansible.builtin.shell:
        cmd: containerd config default>/etc/containerd/config.toml

    - name: Enable and Restart service containerd
      ansible.builtin.systemd:
        state: restarted
        name: containerd
        enabled: true
        daemon-reload: yes

    - name: Add Golang repository key
      apt_key:
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x52b59b1571a79dbc054901c0f6bc817356a3d45e
        state: present

    - name: Add Golang repository
      apt_repository:
        repo: deb https://ppa.launchpadcontent.net/longsleep/golang-backports/ubuntu {{ ansible_distribution_release | lower }} main 
        state: present

    - name: Install Golang
      apt:
        pkg:
          - golang-go
        state: present
        update_cache: true
      become: true

    - name: Clone Hey
      ansible.builtin.git:
        repo: https://github.com/rakyll/hey.git
        dest: /tmp/hey

    - name: Make Hey
      community.general.make:
        chdir: /tmp/hey

    - name: Copy Hey to /usr/bin
      become: yes
      become_user: root
      copy:
        remote_src: yes
        src: /tmp/hey/bin/hey_linux_amd64
        dest: /usr/bin/hey
        owner: root
        mode: '755'
        
    - name: Install faas-cli
      shell: curl -sSL https://cli.openfaas.com | sudo -E sh
