- name: Reset lab environment
  hosts: "localhost"
  tasks:
    - name: Restart docker service
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: true
        name: docker

    - name: Remove docker registry
      shell: docker rm -f registry
      ignore_errors: True

    - name: Start docker registry
      shell: docker run -d -p 5000:5000 --restart always --name registry registry:2

    - name: Swapoff
      shell: swapoff -a

    - name: Reset Kubernetes cluster
      shell: kubeadm reset -f

    - name: Delete kube-config directory
      file:
        path: /root/.kube
        state: absent

    - name: Init Kubernetes cluster
      shell: kubeadm init

    - name: create .kube directory
      become: yes
      become_user: root
      file:
        path: /root/.kube
        state: directory
        mode: 0755

    - name: copy kube config
      become: yes
      become_user: root
      copy:
        remote_src: yes
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        owner: root
      
    - name: untaint master
      become: yes
      become_user: root
      shell: kubectl taint nodes --all node-role.kubernetes.io/master-
      
    - name: Create weavenet
      become: yes
      become_user: root
      shell: kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml

    - name: Git clone OpenFaaS repository
      ansible.builtin.git:
        repo: https://github.com/openfaas/faas-netes.git
        dest: /tmp/faas-netes

    - name: Create openfaas namespaces
      command: kubectl apply -f https://raw.githubusercontent.com/openfaas/faas-netes/master/namespaces.yml

    - name: Create basic-auth for OpenFaaS
      command: kubectl -n openfaas create secret generic basic-auth --from-literal=basic-auth-user=admin --from-literal=basic-auth-password=Hello

    - name: Install OpenFaaS
      command: kubectl apply -f ./
      args:
        chdir: /tmp/faas-netes/yaml

    - name: Install Jaeger
      command: kubectl apply -f https://raw.githubusercontent.com/szefoka/Villany_Kubernetes_Labor/main/yaml/jaegerstack.yaml
      
    - name: Install faas-cli
      shell: curl -sSL https://cli.openfaas.com | sudo -E sh
