---
kind: Service
apiVersion: v1
metadata:
  name: jaeger
  namespace: default
  labels:
    app: jaeger
spec:
  selector:
    app: jaeger
  ports:
  - name: port1
    protocol: TCP
    port: 16686
  type: LoadBalancer
---
kind: Service
apiVersion: v1
metadata:
  name: jaeger-udp
  namespace: default
  labels:
    app: jaeger
spec:
  selector:
    app: jaeger
  ports:
  - name: port-udp
    protocol: UDP
    port: 6831
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: default
spec:
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      hostname: jaeger
      containers:
      - name: jaeger-all-in-one
        image: jaegertracing/all-in-one:latest
        #image: jaegertracing/all-in-one:1.12
        env:
        - name: SPAN_STORAGE_TYPE
          value: "elasticsearch"
        - name: ES_SERVER_URLS
          value: "http://elasticsearch:9200"
        - name: ES_TAGS_AS_FIELDS_ALL
          value: "true"
        - name: QUERY_MAX_CLOCK_SKEW_ADJUSTMENT
          value: "0s"
        ports:
        - containerPort: 16686
        - containerPort: 6831
