apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
    name: rest
  - protocol: TCP
    port: 9300
    targetPort: 9300
    name: nodecomm
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
        ports:
        - containerPort: 9200
          name: rest
        - containerPort: 9300
          name: nodecomm
        env:
          - name: ES_JAVA_OPTS
            value: "-Xms2g -Xmx2g"
          - name: discovery.type
            value: "single-node"
          - name: xpack.security.enabled
            value: "false"
---
kind: Service
apiVersion: v1
metadata:
  name: jaeger-udp
  namespace: default
  labels:
    app: jaeger
spec:
  selector:
    app: jaeger
  ports:
  - name: port-udp
    protocol: UDP
    port: 6831
  type: LoadBalancer
---
kind: Service
apiVersion: v1
metadata:
  name: jaeger
  namespace: default
  labels:
    app: jaeger
spec:
  selector:
    app: jaeger
  ports:
  - name: port1
    protocol: TCP
    port: 16686
    nodePort: 31686
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: default
spec:
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      hostname: jaeger
      containers:
      - name: jaeger-all-in-one
        image: jaegertracing/all-in-one:latest
        #image: jaegertracing/all-in-one:1.12
        env:
        - name: SPAN_STORAGE_TYPE
          value: "elasticsearch"
        - name: ES_SERVER_URLS
          value: "http://elasticsearch:9200"
        - name: ES_TAGS_AS_FIELDS_ALL
          value: "true"
        - name: QUERY_MAX_CLOCK_SKEW_ADJUSTMENT
          value: "0s"
        ports:
        - containerPort: 16686
        - containerPort: 6831
